# Generated by Django 3.2.12 on 2022-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_deparment'),
    ]

    operations = [
        migrations.CreateModel(
            name='deparment_info',
            fields=[
                ('department_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Deparment',
        ),
    ]
