# Generated by Django 3.2.12 on 2022-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220724_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('student_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('fathers_name', models.CharField(max_length=200)),
                ('mothers_name', models.CharField(max_length=200)),
            ],
        ),
    ]
