# Generated by Django 3.2.12 on 2022-07-24 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
