# Generated by Django 3.2.12 on 2022-07-24 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220724_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student_info',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
