# Generated by Django 3.2.12 on 2022-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20220724_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=20, null=True),
        ),
    ]
