# Generated by Django 3.2.12 on 2022-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='BloodGroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='per_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='pre_addresss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
