# Generated by Django 3.2.12 on 2022-07-24 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20220724_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='deparment_info',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='students.deparment_info'),
            preserve_default=False,
        ),
    ]
