# Generated by Django 3.2.12 on 2022-07-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_staff_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_info',
            fields=[
                ('subject_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200)),
                ('deparment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.deparment_info')),
            ],
        ),
    ]
